CREATE TABLE IF NOT EXISTS address
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    zip_code     VARCHAR(255),
    street       VARCHAR(255),
    number       VARCHAR(255),
    complement   VARCHAR(255),
    reference    VARCHAR(255),
    neighborhood VARCHAR(255),
    city         VARCHAR(255),
    state        VARCHAR(255),
    people_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bank_info
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    bank         VARCHAR(255),
    branch       VARCHAR(255),
    account_type VARCHAR(255),
    account      VARCHAR(255),
    digit        VARCHAR(255),
    people_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_bank_info PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS boat_license
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    number       VARCHAR(255),
    people_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_boat_license PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS contact_info
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    email            VARCHAR(255),
    phone1           VARCHAR(255),
    phone2           VARCHAR(255),
    phone3           VARCHAR(255),
    spouse           VARCHAR(255),
    spouse_birthdate date,
    people_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_contact_info PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dependent
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255)                            NOT NULL,
    birth_date   date,
    people_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_dependent PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS drivers_license
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    registration       VARCHAR(255),
    state              VARCHAR(255),
    valid_until        date,
    category           VARCHAR(255),
    first_license_date date,
    issue_date         date,
    people_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_drivers_license PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS education
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    education_level VARCHAR(255),
    institution     VARCHAR(255),
    course          VARCHAR(255),
    period          VARCHAR(255),
    people_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_education PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS firearm
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    sigma_number          VARCHAR(255),
    service_authorization VARCHAR(255),
    people_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_firearm PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS military_identity
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    number         VARCHAR(255)                            NOT NULL,
    issuing_agency VARCHAR(255),
    state          VARCHAR(255),
    issue_date     date,
    valid_until    date,
    registration   VARCHAR(255)                            NOT NULL,
    people_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_military_identity PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS military_people
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    full_name                VARCHAR(255)                            NOT NULL,
    war_name                 VARCHAR(255)                            NOT NULL,
    cpf                      VARCHAR(255)                            NOT NULL,
    birth_date               date,
    birth_month              INTEGER,
    marital_status           VARCHAR(255),
    gender                   VARCHAR(255),
    religion                 VARCHAR(255),
    blood_type               VARCHAR(255),
    rh_factor                VARCHAR(255),
    head_size                VARCHAR(255),
    shoe_size                VARCHAR(255),
    boot_size                VARCHAR(255),
    shirt_size               VARCHAR(255),
    pants_size               VARCHAR(255),
    shorts_size              VARCHAR(255),
    swimwear_size            VARCHAR(255),
    swim_trunks_size         VARCHAR(255),
    organ_donor              BOOLEAN,
    blood_donor              BOOLEAN,
    cas_member               BOOLEAN,
    sismepe_user             BOOLEAN,
    has_accident_certificate BOOLEAN,
    has_chronic_disease      BOOLEAN,
    controlled_medication    BOOLEAN,
    has_allergies            BOOLEAN,
    rank_id                  BIGINT,
    CONSTRAINT pk_military_people PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS military_rank
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    number            INTEGER                                 NOT NULL,
    rank_abbreviation VARCHAR(255)                            NOT NULL,
    rank_name         VARCHAR(255)                            NOT NULL,
    branch            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_military_rank PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS parents
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    mother_name  VARCHAR(255),
    father_name  VARCHAR(255),
    nationality  VARCHAR(255),
    birthplace   VARCHAR(255),
    state        VARCHAR(255),
    people_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_parents PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS qualification
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    course       VARCHAR(255)                            NOT NULL,
    location     VARCHAR(255),
    people_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_qualification PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS service_history
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    entry_date          date,
    service_time        INTEGER,
    accumulated_days    INTEGER,
    total_days          INTEGER,
    total_time          VARCHAR(255),
    arrival_date        date,
    arrival_document    VARCHAR(255),
    last_promotion_date date,
    coaph               VARCHAR(255),
    crvcm               VARCHAR(255),
    rmp                 VARCHAR(255),
    mbm                 VARCHAR(255),
    people_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_service_history PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS voter_info
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    number       VARCHAR(255),
    zone         VARCHAR(255),
    section      VARCHAR(255),
    state        VARCHAR(255),
    people_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_voter_info PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS work_location
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    schedule           VARCHAR(255)                            NOT NULL,
    reduced_work_hours BOOLEAN,
    readapted          BOOLEAN,
    people_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_work_location PRIMARY KEY (id)
);

ALTER TABLE address
    ADD CONSTRAINT uc_address_people UNIQUE (people_id);

ALTER TABLE bank_info
    ADD CONSTRAINT uc_bank_info_people UNIQUE (people_id);

ALTER TABLE boat_license
    ADD CONSTRAINT uc_boat_license_people UNIQUE (people_id);

ALTER TABLE contact_info
    ADD CONSTRAINT uc_contact_info_people UNIQUE (people_id);

ALTER TABLE drivers_license
    ADD CONSTRAINT uc_drivers_license_people UNIQUE (people_id);

ALTER TABLE education
    ADD CONSTRAINT uc_education_people UNIQUE (people_id);

ALTER TABLE military_identity
    ADD CONSTRAINT uc_military_identity_number UNIQUE (number);

ALTER TABLE military_identity
    ADD CONSTRAINT uc_military_identity_people UNIQUE (people_id);

ALTER TABLE military_identity
    ADD CONSTRAINT uc_military_identity_registration UNIQUE (registration);

ALTER TABLE military_people
    ADD CONSTRAINT uc_military_people_cpf UNIQUE (cpf);

ALTER TABLE parents
    ADD CONSTRAINT uc_parents_people UNIQUE (people_id);

ALTER TABLE service_history
    ADD CONSTRAINT uc_service_history_people UNIQUE (people_id);

ALTER TABLE voter_info
    ADD CONSTRAINT uc_voter_info_people UNIQUE (people_id);

ALTER TABLE work_location
    ADD CONSTRAINT uc_work_location_people UNIQUE (people_id);

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE bank_info
    ADD CONSTRAINT FK_BANK_INFO_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE boat_license
    ADD CONSTRAINT FK_BOAT_LICENSE_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE contact_info
    ADD CONSTRAINT FK_CONTACT_INFO_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE dependent
    ADD CONSTRAINT FK_DEPENDENT_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE drivers_license
    ADD CONSTRAINT FK_DRIVERS_LICENSE_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE education
    ADD CONSTRAINT FK_EDUCATION_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE firearm
    ADD CONSTRAINT FK_FIREARM_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE military_identity
    ADD CONSTRAINT FK_MILITARY_IDENTITY_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE military_people
    ADD CONSTRAINT FK_MILITARY_PEOPLE_ON_RANK FOREIGN KEY (rank_id) REFERENCES military_rank (id);

ALTER TABLE parents
    ADD CONSTRAINT FK_PARENTS_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE qualification
    ADD CONSTRAINT FK_QUALIFICATION_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE service_history
    ADD CONSTRAINT FK_SERVICE_HISTORY_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE voter_info
    ADD CONSTRAINT FK_VOTER_INFO_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);

ALTER TABLE work_location
    ADD CONSTRAINT FK_WORK_LOCATION_ON_PEOPLE FOREIGN KEY (people_id) REFERENCES military_people (id);